shardingsphere:
  datasource:
    name: sharding
    driver-class-name: com.mysql.cj.jdbc.Driver
    hosts: localhost,localhost
    url-pattern: jdbc:mysql://{HOST}/${shardingsphere.datasource.name}{DS_NUM}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password:
